---

sudo: required
dist: trusty
language: generic


before_install:
  - sudo apt-get --assume-yes --force-yes install software-properties-common
  - sudo apt-add-repository --yes ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get --assume-yes --force-yes install ansible

  # print memory utilization and running processes
  - sudo free
  - sudo ps aux


script:
  - ansible-playbook
    -v
    -i inventory/localhost
    --connection=local
    --sudo
    --vault-password-file=ansible-password.txt
    provision/db-deploy.yml


# vim: set ts=8 sts=2 sw=2 et:
